### ISSUE TITLE
ESP8266 on an ESP-01 board - setup as "8266 generic" not recognized

### ISSUE THREAD

**Issue by PaulskPt** [khoih-prog/ESP_AT_Lib#2]
First of all: thank you for publishing this repo.

I installed this library in the Arduino IDE v1.8.13 for MS Windows 10.

Next I loaded the example sketch: ConnectWiFi.ino .

![Arduino_ESP_AT_Lib_examples_3](https://user-images.githubusercontent.com/9107950/142408640-4800f492-ad1b-4190-8b19-72cf1f1fa7ee.png)

I am using an ESP-01 board with an ESP8266 to provide WiFi connection to a Raspberry Pi Pico on a Maker Pi Pico board.

![ESP-01_on_Maker_Pi_Pico_board](https://user-images.githubusercontent.com/9107950/142409070-7e2a2005-a0b0-4b8e-b841-5b4797b497ac.png)

The build of the sketch aborted with the following error description:

```
ConnectWiFi:269:4: error: #error Unknown or unsupported Board. Please check your Tools->Board setting.
  269 |   #error Unknown or unsupported Board. Please check your Tools->Board setting.
      |    ^~~~~
exit status 1
#error Unknown or unsupported Board. Please check your Tools->Board setting.
```
Board selected:

![ESP-01_in_Arduino_IDE_Tools_Boards_](https://user-images.githubusercontent.com/9107950/142407437-0cb602da-cc97-4a0a-9b17-49e2d6c55359.png)

This error appears 'odd' to me because the text in the heading of this script (line 3) reads: 

``` For ESP8266/ESP32-AT-command running shields```

The ESP8266 on the ESP-01 board is, to my opinion such a board.

Finally:
When you decide to modify the script to cover the ESP-01 board, please modify also line 2 of the same script which has, as far as I can deduct, a copy-and-paste error. Line 2 reads: "HTTPGET.ino". It should read: "ConnectWiFi.ino".

Greetings,
Paulus (@Paulskpt)

**Comment by khoih-prog** [comment]
Hi @PaulskPt 

First of all, thanks to your interest in the library

I'm sorry to say that you are totally mistaken how to use the library, which is supporting these [**Currently Supported Boards**](https://github.com/khoih-prog/ESP_AT_Lib#currently-supported-boards) as the main board along with ESP8266-01 as independent WiFi shield. This can't be used with ESP8266 core as you're trying to use.

I suggest you do some more research on how to use ESP8266 with AT-commands. Then post the `request for help` in some forums, such as Arduino, ESP8266.

Good Luck,

**Comment by PaulskPt** [comment]
Hi @khoih-prog,
I take the liberty of giving a reply to what you wrote before you closed this issue.
Thank you for your kind response and the 'invalid' label. 
About being 'totally mistaken how to use the library, which is supporting these Currently Supported Boards as the main board...' I answer:
As I wrote in my Post: I am using a Raspberry Pi Pico as a main board, listed in the list of boards your link is directing to:

![image](https://user-images.githubusercontent.com/9107950/142724923-714bcd14-a26c-4802-9f95-6adbfd5399e6.png)

What I don't like in your reaction  is being patronized. I did my research as you can see at the end of my post about the possible cut-and-past error - that did not pass my reading unnoticed (on which you did not reply). You did not need to put an 'invalid' label to close this issue. Before I posted this issue, I did my homework. I also understood that the ESP-01 was going to do an independent job as a WiFi shield. That's why I bought the ESP-01 board in the first place. Yes, maybe I mixed things. I am sorry if I bothered you with posting this issue. 
About your reaction to AT-commands I answer: around 1981 I was already using Hayes modems with AT-commands, connected to an IBM PC, b4 there was the internet (ref: https://waag.org/en/article/30-years-internet-netherlands), to remotely transfer software that I created into in a companies system; order remotely to compile it there and put the resulting app modules where the company workers could use them. I worked for the Dutch FCC in various positions. For some time at the department that went out to importers; select samples of modems; have those modems inspected to their proclaimed conformity of EU regulations; take corrective steps in the case the modems did not comply. Within the Dutch FCC I was the founder of a project to have our field engineers being equipped with modems to work remotely from home. So, I think I have some 'baggage' at that point too. 

I also which you good luck.

**Comment by khoih-prog** [comment]
![Selection_079](https://user-images.githubusercontent.com/57012152/142740144-c34e1e38-da41-413e-a9e2-6c5345039bfc.png)

![Selection_080](https://user-images.githubusercontent.com/57012152/142740147-7afc2aae-8049-419c-9d13-b618a11a08d8.png)
